//! expert_bundle — formato bundle contiguo de expertos MoE (11.2, PowerInfer §3.1).
//!
//! Problema: en el GGUF los bytes de un experto están dispersos — 3 bancos
//! (gate/up/down) × N capas repartidos por el fichero, cada uno una ventana
//! dentro de un tensor `ffn_*_exps` grande. Con offload por-experto, cada
//! fetch = page-faults aleatorios sobre el mmap (o read de regiones no
//! contiguas del copy-once bank). PowerInfer (expert_bundle.cpp) reordena
//! los pesos de TODOS los expertos a slots CONTIGUOS fixed-size en un
//! fichero aparte: un fetch = UNA lectura secuencial de `slot_bytes`.
//!
//! Formato (adaptado a nuestro stack — sin repack q4_bl, slots crudos):
//!
//!   [header 64B mágico "ZBND" v1]
//!   [payload: slots contiguos, orden determinista
//!    slot_index = kind + expert*3 + layer*E*3
//!    kind: 0=gate 1=up 2=down (BankKind)]
//!   cada slot: `slot_bytes` (padded a 4096) de pesos crudos del experto
//!   (bytes canónicos del expertSlice — escalas compuestas si el preset
//!   las tenía externas).
//!
//! El header lleva los metadatos para derivar offsets SIN índice aparte
//! (n_layers, n_experts, slot_bytes por kind puede diferir: gate/up/down
//! tienen shapes distintas ⇒ slots por-matriz, offsets via kind_offset[]
//! precomputados en el header).
//!
//! Runtime: `BundleSource` abre el bundle con mmap (o fd + pread para el
//! fetch async) y expone `expertSlice(layer, kind, expert)` con la misma
//! semántica que `BankRef.expertSlice` — drop-in para el loadFn del
//! OffloadCache y el stage del expert_streamer.
//!
//! Builder: bundle format generated by `moe-make-bundle` CLI (see docs).
//! Breadcrumbs gated (DEBUG_LEVEL, tag [moe_bundle]) — regla debug.zig.
//!
//! Flags (CLI/engine, wiring siguiente paso):
//!   --expert-bundle <path> / ZIG_AI_BUNDLE=1     — usar bundle como fuente
//!   ZIG_AI_BUNDLE_PREFETCH=0                      — desactivar prefetch
//!                                                   cross-layer (4.9 reusa)

const std = @import("std");
const gguf = @import("gguf");
const gguf_moe = @import("gguf_moe");
const debugz = @import("debug");

// FFI glibc (patrón host_bank.zig:10-11 — std.posix.pread cambió en 0.16)
extern "c" fn pread(fd: c_int, buf: [*]u8, count: usize, offset: i64) isize;
extern "c" fn open64(path: [*:0]const u8, flags: c_int, ...) c_int;

pub const MAGIC = "ZBND";
pub const VERSION: u32 = 3;
/// Alineación entre kinds (payload empieza page-aligned tras el header).
/// NOTA v3: SIN pad por-slot — el stride del slot == slot_bytes[k] exacto
/// para que las ventanas del bundle sean drop-in del gather (stride del
/// GGUF). El pad 4096 por-slot (v2) solo servía para pread O_DIRECT
/// per-slot; ese camino no existe en el wiring UVA/pread-buffered actual
/// y el stride desincronizaba el gather (847872 ≠ 844800 en 21B Q3_K_S).
pub const IO_ALIGN: usize = 4096;

pub const BundleError = error{
    InvalidMagic,
    UnsupportedVersion,
    LayoutMismatch,
    SlotOutOfRange,
    EmptyBundle,
    OpenFailed,
};

/// Header fijo 64B — todo little-endian, pad explícito a 64.
pub const Header = extern struct {
    magic: [4]u8 = MAGIC.*,
    version: u32 = VERSION,
    n_layers: u32,
    n_experts: u32,
    /// Bytes de slot por kind (3: gate, up, down) = MÁXIMO sobre todas las
    /// capas (PowerInfer append_zero style: los modelos con FFN heterogéneo
    /// por tramo — SmallThinker — rellenan con pad de ceros; el tamaño
    /// ÚTIL por capa se deriva del GGUF fuente, no del bundle).
    slot_bytes: [3]u32,
    /// Offset del payload dentro del fichero (tras el header, 64B).
    payload_offset: u32 = 64,
    _pad: [32]u8 = [_]u8{0} ** 32,
};

comptime {
    if (@sizeOf(Header) != 64) @compileError("Header debe ser 64B");
}

/// Padding de un tamaño a IO_ALIGN (alineación de INICIO de banco; los
/// slots internos van SIN pad en v3).
pub fn padAlign(bytes: usize) usize {
    return (bytes + IO_ALIGN - 1) / IO_ALIGN * IO_ALIGN;
}

/// Orden determinista de slots — espejo del layout de PowerInfer
/// (matrix_id + expert_id*N_MATRICES + layer_id*n_experts*N_MATRICES).
pub const N_KINDS: usize = 3; // gate, up, down

pub fn slotIndex(layer: u32, kind: usize, expert: u32, n_experts: u32) usize {
    std.debug.assert(kind < N_KINDS);
    return kind + @as(usize, expert) * N_KINDS +
        @as(usize, layer) * @as(usize, n_experts) * N_KINDS;
}

/// Offsets absolutos de cada matriz dentro del payload: los slots de un
/// mismo kind son contiguos por bloques de layer (layout por-matriz de
/// PowerInfer: todos los gate de capa 0, luego up, down; después capa 1).
/// Esto mantiene 1 lectura secuencial por fetch.
pub fn kindBaseOffset(hdr: Header, kind: usize) usize {
    // Espejo EXACTO del builder: posiciones ABSOLUTAS — tras cada banco la
    // posición se alinea a 4096 (el payload empieza en 64 ⇒ el pad efectivo
    // por banco es 4096−(pos mod 4096), NO padAlign del tamaño del banco).
    // El builder (moe-make-bundle) es la autoridad del formato; el
    // test de integridad valida contra él.
    var off: usize = hdr.payload_offset;
    for (0..kind) |k| {
        off += kindSlotCount(hdr, k) * hdr.slot_bytes[k];
    }
    return off;
}

pub fn kindSlotCount(hdr: Header, kind: usize) usize {
    _ = kind; // mismo count para todos los kinds (L×E slots c/u)
    return @as(usize, hdr.n_layers) * @as(usize, hdr.n_experts);
}

/// Offset absoluto del slot (layer, kind, expert) en el FICHERO.
pub fn slotFileOffset(hdr: Header, layer: u32, kind: usize, expert: u32) usize {
    // Slots del kind `kind` ordenados (layer, expert): capa-major, stride
    // = slot_bytes[kind] EXACTO (v3 sin pad — drop-in del gather).
    // kindBaseOffset ya incluye payload_offset; NO se suma de nuevo.
    const idx_in_kind = @as(usize, layer) * @as(usize, hdr.n_experts) + expert;
    return kindBaseOffset(hdr, kind) +
        idx_in_kind * hdr.slot_bytes[kind];
}

/// ── Fuente runtime ─────────────────────────────────────────────────────

/// Fuente de bytes de expertos desde un bundle. Mantiene el fd abierto para
/// fetches O_DIRECT/pread async (el worker io_uring de 11.2-p2); también
/// soporta mmap perezoso para lecturas densas (builder de caché inicial).
pub const BundleSource = struct {
    hdr: Header,
    path: []u8,
    fd: c_int,
    file_len: usize,
    /// mmap perezoso (activado con ensureMmap para lecturas densas).
    mmap: ?std.Io.File.MemoryMap = null,
    mm_io: ?std.Io = null,
    allocator: std.mem.Allocator,

    pub fn open(allocator: std.mem.Allocator, path: []const u8) BundleError!BundleSource {
        const O_RDONLY: c_int = 0;
        var pbuf: [4096]u8 = undefined;
        const pz = std.fmt.bufPrintZ(&pbuf, "{s}", .{path}) catch return BundleError.OpenFailed;
        const fd = open64(pz.ptr, O_RDONLY);
        if (fd < 0) return BundleError.OpenFailed;
        var hdr: Header = undefined;
        const n = pread(fd, @ptrCast(std.mem.asBytes(&hdr).ptr), @sizeOf(Header), 0);
        if (n < @sizeOf(Header)) {
            _ = std.os.linux.close(@intCast(fd));
            return BundleError.InvalidMagic;
        }
        if (!std.mem.eql(u8, &hdr.magic, MAGIC)) {
            _ = std.os.linux.close(@intCast(fd));
            return BundleError.InvalidMagic;
        }
        if (hdr.version != VERSION) return BundleError.UnsupportedVersion;
        if (hdr.n_layers == 0 or hdr.n_experts == 0) return BundleError.EmptyBundle;

        // Tamaño del fichero vía statx (0.16: fstat linux wrapper eliminado).
        const len: usize = blk: {
            var sx: std.os.linux.Statx = undefined;
            const rc = std.os.linux.statx(fd, "", std.os.linux.AT.EMPTY_PATH, .{ .SIZE = true }, &sx);
            if (rc != 0) return BundleError.OpenFailed;
            break :blk @intCast(sx.size);
        };

        const path_owned = allocator.dupe(u8, path) catch return BundleError.OpenFailed;
        return .{
            .hdr = hdr,
            .path = path_owned,
            .fd = fd,
            .file_len = len,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *BundleSource) void {
        if (self.mmap) |*mm| {
            mm.destroy(self.mm_io.?);
            self.mmap = null;
        }
        _ = std.os.linux.close(@intCast(self.fd));
        self.allocator.free(self.path);
    }

    /// Slice del slot COMPLETO (slot_bytes[k], incluye pad de ceros si el
    /// modelo es heterogéneo). El consumidor conoce los bytes útiles por
    /// capa (deriva del GGUF fuente) — el bundle garantiza slot fijo.
    /// SIN mmap: aloca + pread (caller libera con gpa.free). CON mmap:
    /// vista prestada del mapping (caller NO libera — usar wasAllocated()
    /// para decidir en tests/consumidores genéricos).
    pub fn expertSlice(self: *const BundleSource, layer: u32, kind: gguf_moe.BankKind, expert: u32) BundleError![]const u8 {
        const k: usize = @intFromEnum(kind);
        const off = slotFileOffset(self.hdr, layer, k, expert);
        const len: usize = self.hdr.slot_bytes[k];
        if (off + len > self.file_len) return BundleError.SlotOutOfRange;
        if (self.mmap) |*mm| {
            return mm.memory[off..][0..len];
        }
        // Sin mmap: pread directo (fetch de 1 slot — camino async-friendly).
        const buf = self.allocator.alloc(u8, len) catch return BundleError.OpenFailed;
        const n = pread(self.fd, buf.ptr, len, @intCast(off));
        if (n < @as(isize, @intCast(len))) {
            self.allocator.free(buf);
            return BundleError.SlotOutOfRange;
        }
        return buf; // caller libera (contrato loadFn del OffloadCache)
    }

    /// true si expertSlice habría alocado (camino pread) — para que el
    /// caller genérico sepa si liberar o no.
    pub fn slicesAreBorrowed(self: *const BundleSource) bool {
        return self.mmap != null;
    }

    /// Pread a buffer EXTERNO (fetch async del worker 11.2-p2 + stage
    /// directo a pinned): devuelve bytes leídos (slot_bytes útiles).
    pub fn readExpertInto(self: *const BundleSource, layer: u32, kind: gguf_moe.BankKind, expert: u32, dst: []u8) BundleError!usize {
        const k: usize = @intFromEnum(kind);
        const len: usize = self.hdr.slot_bytes[k];
        if (dst.len < len) return BundleError.SlotOutOfRange;
        const off = slotFileOffset(self.hdr, layer, k, expert);
        const n = pread(self.fd, dst.ptr, len, @intCast(off));
        if (n < @as(isize, @intCast(len))) return BundleError.SlotOutOfRange;
        return len;
    }

    /// mmap del payload completo (lecturas densas: warm-up de cache, builder).
    /// Requiere el `io` del caller (MemoryMap 0.16 es Io-aware; se guarda
    /// para el deinit).
    pub fn ensureMmap(self: *BundleSource, io: std.Io) BundleError!void {
        if (self.mmap != null) return;
        const dir = std.Io.Dir.cwd();
        const file = dir.openFile(io, self.path, .{ .mode = .read_only }) catch
            return BundleError.OpenFailed;
        const mm = std.Io.File.MemoryMap.create(io, file, .{
            .len = @intCast(self.file_len),
            .protection = .{ .read = true },
            .populate = false,
        }) catch {
            file.close(io);
            return BundleError.OpenFailed;
        };
        // El fd del file queda propiedad del mapping (patrón GgufFile).
        self.mmap = mm;
        self.mm_io = io;
    }
};

/// ── Validación cruzada GGUF ↔ bundle ────────────────────────────────────

/// Verifica que el bundle corresponde al GGUF fuente (n_layers/n_experts y
/// slot_bytes esperados por kind derivados de layerSpec de TODAS las capas
/// MoE). Es el gate de integridad del builder y del wiring runtime.
pub fn validateAgainstGguf(
    src: *const BundleSource,
    g: *const gguf.GgufFile,
    allocator: std.mem.Allocator,
) BundleError!void {
    var n_moe_layers: u32 = 0;
    var n_experts: u32 = 0;
    for (0..32 * 1024) |il| {
        if (!gguf_moe.isMoeLayer(g, il)) continue;
        const spec = gguf_moe.layerSpec(g, il) catch continue;
        n_moe_layers += 1;
        n_experts = @intCast(spec.n_expert);
        // slot_bytes por kind = MÁXIMO sobre capas: cada capa debe caber
        // (<=) en el slot. Heterogéneo ⇒ ceros de relleno (v2).
        const cur: [3]usize = .{
            spec.gate.expertBytes(),
            spec.up.expertBytes(),
            spec.down.expertBytes(),
        };
        for (0..N_KINDS) |k| {
            if (cur[k] > src.hdr.slot_bytes[k]) {
                debugz.dbg.printLevel(.info, "[moe_bundle] mismatch capa {d} kind {d}: gguf {d} > slot bundle {d} bytes\n", .{ il, k, cur[k], src.hdr.slot_bytes[k] });
                return BundleError.LayoutMismatch;
            }
        }
    }
    if (src.hdr.n_layers != n_moe_layers or src.hdr.n_experts != n_experts) {
        debugz.dbg.printLevel(.info, "[moe_bundle] layout global: bundle L{d}E{d} vs gguf L{d}E{d}\n", .{ src.hdr.n_layers, src.hdr.n_experts, n_moe_layers, n_experts });
        return BundleError.LayoutMismatch;
    }
    _ = allocator;
}

// ── Tests ────────────────────────────────────────────────────────────────

const testing = std.testing;

test "slotIndex orden determinista kind-expert-layer" {
    // kind + expert*3 + layer*E*3 — sin colisiones en un caso pequeño.
    const E: u32 = 4;
    var seen = std.AutoHashMap(usize, void).init(testing.allocator);
    defer seen.deinit();
    for (0..2) |l| for (0..E) |e| for (0..N_KINDS) |k| {
        const idx = slotIndex(@intCast(l), k, @intCast(e), E);
        try testing.expect((try seen.getOrPut(idx)).found_existing == false);
    };
}

test "padAlign 4096" {
    try testing.expectEqual(@as(usize, 4096), padAlign(1));
    try testing.expectEqual(@as(usize, 4096), padAlign(4096));
    try testing.expectEqual(@as(usize, 8192), padAlign(4097));
}

test "slotFileOffset monotónico dentro de kind" {
    var hdr: Header = .{
        .n_layers = 2,
        .n_experts = 4,
        .slot_bytes = .{ 4096, 4096, 8192 },
    };
    _ = &hdr;
    // gate de (l0,e0) < gate de (l0,e1) < ... < gate (l1,e3) < up (l0,e0)
    const g00 = slotFileOffset(hdr, 0, 0, 0);
    const g03 = slotFileOffset(hdr, 0, 0, 3);
    const g13 = slotFileOffset(hdr, 1, 0, 3);
    const up00 = slotFileOffset(hdr, 0, 1, 0);
    try testing.expect(g00 < g03);
    try testing.expect(g03 < g13);
    try testing.expect(g13 < up00); // kind-major tras todos los gate
}
